name: compile
on:
  push:
    branches:
      - "develop"
  pull_request:
    types:
      - closed
    branches:
      - "develop"
      - "main"
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js
        uses: actions/setup-node@v3
        id: pnpm-cache
        with:
          node-version: 18
          cache: "pnpm"
      - name: Cache NPM dependencies # (2)
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_modules
          key: modules

      - name: Install dependencies # (3)
        if: ${{steps.pnpm-cache.outputs.cache-hit != 'true'}}
        run: npm ci
