name: compile
on:
  push:
    branches:
      - "develop"
  pull_request:
    types:
      - closed
    branches:
      - "develop"
      - "main"
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Install dependencies
        run: npm install
